### ISSUE TITLE
Support for platform-dependent source directories

### ISSUE THREAD

**Issue by sjrd** [sjrd/sbt-dynscalajs#10]
It might be useful to support platform-dependent source directories out of the box, for example, `src/main/scala-jvm/` and `src/main/scala-js/`.

This should be very easy to implement. Just add something like
```scala
unmanagedSourceDirectories += {
  // something depending on dynScalaJSVersion.value
}
```

**Comment by fommil** [comment]
This would be an excellent addition to this plugin, which I admit looks like it dramatically simplifies things for us contributors and maintainers!

**Comment by fommil** [comment]
thank you so much!
